- hachoir/core/log.py
The value of `ENOENT` is architecture-dependent, so don't assume it's always 2.
Found using [pydiatra](https://github.com/jwilk/pydiatra).
> Don't hardcode errno constant

- hachoir/metadata/metadata.py
- tests/test_metadata.py
Usage is almost identical to exportPlaintext. Exports metadata in an easy to access dictionary.
I've been using this modification with the Python 2 version of Hachior in Watcher for a few months now and it is very handy. I've tested this commit to work on MKV and MP4 movies as well as a handful of image formats using Python 3.6.0 on Windows 10.
```
>>> from hachoir.parser import createParser
>>> from hachoir.metadata import extractMetadata
>>> parser = createParser('/home/nsb/images/wallpaper/nebula.jpg')
>>> extractor = extractMetadata(parser)
>>> metadata = extractor.exportDictionary(human=False)
>>> print(json.dumps(metadata, indent=2))
{
"Metadata": {
"width": "2560",
"height": "1600",
"image_orientation": "Horizontal (normal)",
"bits_per_pixel": "24",
"pixel_format": "YCbCr", …
```
> Add method to export metadata in dictionary

- hachoir/editor/typed_field.py
- hachoir/stream/output.py
Also fix editing in general (writing of `bytes` as `chr` is no good on Python3).
> Fix EditableTimestampMac32 field editing

- hachoir/parser/file_system/ext2.py
This change fixes a bug triggered when pressing ' ' key in urwid
interface on inode[1]/block[0] in group[0] for digging root directory.
How to reproduce:
1. make an input file:
$ dd if=/dev/zero of=a.ext2 count=5000 bs=1024
$ mkfs.ext2 a.ext2
2. run urwid interface,
3. expand group[0] with enter key,
4. open inode[1]block[0] with space key
5. You will get following error messages and urwid interface stops.
Pending messages:
[*][err!] Error getting description of /: 'Directory' object has no attribute 'PARSER_TAGS'
Traceback (most recent call last):
File "/home/yamato/var/hachoir3-github/hachoir/parser/parser.py", line 76, in _getDescription
self._description = self.createDescription()
File "/home/yamato/var/hachoir3-github/hachoir/parser/parser.py", line 51, in createDescription
return …
> ext2: fix directory digging

- doc/.gitignore
- doc/conf.py
- doc/developer.rst
- hachoir/field/field.py
Previously we had handwritten documentation for the `Field` class. This
starts the process of auto-generating documentation from source code as
part of the normal doc generation.
> Generate `Field` docs from soure code.

- doc/urwid.rst
- setup.py
Fixes #35.
Can be tested locally with `pip install . .[urwid]`.
> Indicate specific urwid version required for hachoir-urwid.

- hachoir/metadata/metadata.py
- tests/test_metadata.py
Since Dict.values is a property, then MultipleMetadata.iterGroups should return it properly. Now when called it crashes with:
```
/hachoir/metadata/metadata.py line 246 in iterGroups
return iter(self.__groups.values())
TypeError: 'list' object is not callable
```
> Fix for calling Dict.values property from MultipleMetadata.iterGroups

- hachoir/core/tools.py
- hachoir/field/__init__.py
- hachoir/field/timestamp.py
- hachoir/metadata/video.py
- hachoir/parser/video/asf.py
- tests/test_metadata.py
Parsed duration for ASF/WMV files is usually wrong. As an example, the parsed metadata for the test demo file "matrix_ping_pong.wmv" says it lasts 1:47.258, but players show it's length as 1:43 or 1:44 (depending which way they round).
This is because the "play_duration" field includes the preroll/buffering time. Thus, to get the actual duration of the video, we must subtract the "preroll" field from the "play_duration" field.
Additional complication: While the "play_duration" and "send_duration" fields are 64-bit integers 100ns counts, "preroll" is a 64-bit integer *millisecond* count. So new code is needed to deal with that.
> Fix for ASF/WMV duration.

- hachoir/parser/misc/pdf.py
It would be an error, but this case only happens inside another error condition so it's not particularly problematic
> Fix SyntaxWarning in 3.8

- hachoir/stream/output.py
Synchronize maximum copy bits count with the fieldset limit the config.
This assertion prevented me from rewriting sets of 256 raw bits due to the 128-bit limit.
The size limit when yielding an instance of RawBits is 256 bits, so imho it makes sense to synchronize with that value.
> Synchronize maximum copy bits count with the fieldset limit

- hachoir/editor/field.py
- hachoir/stream/output.py
- tests/test_editor.py
The current implementation sometimes attempts to write a set of bytes (which is more efficient) when the input size is a multiple of 8. However, when the output stream is not aligned to bytes (e.g. because some bits have been written), this causes a crash in `hachoir/editor/output.py`.
This PR does the following:
1. Detect when the target address is not byte-aligned, and request bits to be written if found true.
2. Disable the byte-writing optimization altogether.
The last item could be considered a work-around (what I'm trying to do works with this PR). However, when updating checks all along the regular implementation path (which usually involves checking whether `output._bit_pos % 8 != 0`, otherwise we eventually end up in `OutputStream.writeBytes` on line 143, which raises a …
> Hachoir.editor: Allow writing unaligned bitstreams

- hachoir/parser/guess.py
- hachoir/stream/input_helper.py
[_Telethon_](https://github.com/LonamiWebs/Telethon) uses _hachoir_ to extract metadata from audio and video files. But I read that it only does so for files on the local disk since _hachoir_ doesn't create parsers from byte arrays and byte streams. So I added the ability to create streams from the passed filename, so the parsers could be created from byte array and streams.
Two things:
- The context manager closes the file when it exits, so it also closes BytesIO files. But I don't know if that's the expected outcome, or the file's expected to be closed even if it's a BytesIO object.
- I only tried passing the parser to `extractMetadata`, and that worked without a hitch. But I don't know if that'd be the case for other functions too. But since the stream gets constructed correctly, I …
> Added passing byte stream to FileInputStream

- doc/install.rst
The urwid website moved without leaving a forwarding address, so the link was broken.
Fix it.
> Update the urwid link

- hachoir/field/string_field.py
Original code would yield a:
"[err!]: Unable to create value: can't concat str to bytes"
which would subsequently lead to a:
"[err!]: Error during metadata extraction: 'NoneType' object has no attribute 'strip'" and rightfully so.
This will resolve that error 😁
> fix bytes concat on repair

- hachoir/parser/misc/ttf.py
- tests/test_parser.py
This PR:
* Adds support to the ttf parser for OpenType fonts (same content, different magic number)
* Allows the parser to unpack the `maxp`, `hhea`, `OS/2`, `post`, `cmap` and `DSIG` tables.
> Improve OpenType/TrueType support

- hachoir/parser/image/jpeg.py
Suggested fix for #67.
Set the size of an JpegImageData section with no terminator to the remainder of the stream,
on the assumption that the file is truncated in the middle of the JpegImageData and so the rest
of the file is its data. This avoids the JpegImageData being parsed to calculate it's size,
and hopefully prevents the corrupted section needing to be parsed at all for most operations.
If the JpegImageData is explicitly parsed the memory blowup and parsing errors will still happen,
but that seems like the expected outcome of parsing a large corrupt section rather than a surprise
that happens when checking for fields.
> Set size of truncated JpegImageData to rest of stream

- hachoir/field/timestamp.py
Datetime can't be created with 0 value for day and/or month. This should cause the value to default to 1 if the value is 0.
> Default date info for TimeDateMSDOS32

- hachoir/parser/archive/lzx.py
- hachoir/parser/archive/zlib.py
The LZX decoder was incorrectly outputting `str` instead of a `bytes` type. Furthermore, it was improperly handling Intel jump fixups causing the output data to be subtly corrupted.
This patch fixes both issues and has been tested by exporting `uncompressed_data` from https://github.com/pushcx/corefonts/blob/master/arial32.exe and checking the output against cabextract's output.
> Fix LZX decompression

- hachoir/parser/program/exe_pe.py
I'm using hachoir in my project and just recently came across a failure because the `PE` exe parser only supports the optional `PE32` header, not the `PE32+` one.
Interestingly this is already marked in the code with a TODO, and adding support for it is relatively simple by just following the specification in https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#optional-header-image-only.
I've tested that with these changes applied, the previously failing exe file can now be parsed correctly.
> Support PE32+ optional header

- hachoir/parser/container/mp4.py
I've got some *.mov files from a (rather old) Kodak EasyShare C533 camera, which have "skip" as the container's first atom, rather than "ftyp", "moov", or "free". They therefore don't pass the check in `hachoir.parser.container.MP4File.validate()`. This initial "skip" atom seems to contain some metadata like camera model name, and is followed by an "mdat" occupying most of the file, and then finally by a "moov".
I use `hachoir` to extract movie's duration and timestamp, and it works fine if `validate()` method is tweaked to allow "skip" as the initial atom. (Apparently, all the needed info is in "moov" at the end of the file).
Admittedly, "skip" doesn't look very characteristic of a movie file, but we already have "free" on the list, so it shouldn't make things much worse.
> Allow QuickTime movies to start with "skip" atom

- hachoir-list
- hachoir/listtool.py
This adds the `hachoir-list` command-line tool which just prints all parsed fields. This text output allows to e.g. use normal shell tools like `diff` and `grep` to analyze parsed files.
> Add hachoir-list tool

- doc/index.rst
- doc/list.rst
This adds some basic documentation for the hachoir-list tool from https://github.com/vstinner/hachoir/pull/102 .
> Add documentation for hachoir-list tool

- hachoir/parser/image/xcf.py
3 suggestions :
1. fix for using xcf version > 2 (last is 23)
2. Added some new edition on enums
3. gitlab link on comment (cvs is too old)
> Some updates on xcf file
